// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: user_error.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Api_User_V1_UserServiceErrorReason: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case userNotFound // = 0
  case userIsFreeze // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .userNotFound
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .userNotFound
    case 1: self = .userIsFreeze
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .userNotFound: return 0
    case .userIsFreeze: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Api_User_V1_UserServiceErrorReason: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Api_User_V1_UserServiceErrorReason] = [
    .userNotFound,
    .userIsFreeze,
  ]
}

#endif  // swift(>=4.2)

#if swift(>=5.5) && canImport(_Concurrency)
extension Api_User_V1_UserServiceErrorReason: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Api_User_V1_UserServiceErrorReason: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "USER_NOT_FOUND"),
    1: .same(proto: "USER_IS_FREEZE"),
  ]
}
